### ISSUE TITLE
Workflow non funzionante

### ISSUE THREAD

**Issue by cristian-5** [csunibo/typst-thesis#1]
Provando a usare la repo principale di Typst come repo del docker image non trova l'immagine. Io mi ero fidato sulla base che vedevo dei file di docker esposti nella repo ma a quanto pare o non c'è l'immagine per il workflow o è rotta; quindi per ora non funziona.

**Comment by cristian-5** [comment]
@foxyseta

**Comment by foxyseta** [comment]
Provo a guardarci appena ho tempo👍

**Comment by lucat1** [comment]
Devi usare `ghcr.io/typst/typst` per l’immagine. Di base usa il registry di docker.io e non quello di github (`ghcr.io`)

**Comment by cristian-5** [comment]
aggiustato, ora puoi per piacere aggiungerlo qua https://github.com/csunibo/.github/blob/main/profile/README.md

**Comment by foxyseta** [comment]
Fatto. Ho anche esteso i diritti a tutto il gruppi di @csunibo/esperti-composizione-documenti perché quando non fai nulla come prefedinito ti mette l'unico con accesso alla repository. Ricordati di farlo tu per futuri progetti.
